### ISSUE TITLE
Guns command not working from Command Palette

### ISSUE THREAD

**Issue by sanjarcode** [ironcev/without-guns-for-vs-code#23]
Guns with and guns without command not working.
VSCode shows an error: 

![Screenshot from 2020-05-20 18-21-07](https://user-images.githubusercontent.com/48156230/82448003-b8a14400-9ac6-11ea-979b-551122bf5944.png)

I'm running Ubuntu 18.04, VScode version 1.45.1

**Comment by ironcev** [comment]
Thanks for reporting the issue @sanjarcode! The issue is reproducible on Windows 10 in the same VSCode version. I'll take a look.

**Comment by ironcev** [comment]
Looking at the logs (Cmd/Ctrl+Shift+P -> Show Logs -> Extension Host):

`[exthost] [error] TypeError: Cannot read property 'themes' of undefined
	at c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\SyntaxHighlightingGunController.js:69:68
	at Array.filter (<anonymous>)
	at SyntaxHighlightingGunController.getEditorForegroundColor (c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\SyntaxHighlightingGunController.js:69:14)
	at SyntaxHighlightingGunController.createTokenColorCustomizations (c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\SyntaxHighlightingGunController.js:16:42)
	at SyntaxHighlightingGunController.getGunlessSettings (c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\SyntaxHighlightingGunController.js:13:58)
	at SyntaxHighlightingGunController.takeTheGunCore (c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\ConfigurationDependentGunController.js:22:41)
	at SyntaxHighlightingGunController.takeTheGun (c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\GunController.js:14:14)
	at c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\WithoutGunsExtension.js:17:68
	at Array.forEach (<anonymous>)
	at WithoutGunsExtension.takeTheGuns (c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\WithoutGunsExtension.js:17:29)
	at c:\Users\USER\.vscode\extensions\ironcev.without-guns-0.3.1\out\src\extension.js:20:30
	at e._executeContributedCommand (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:627:894)
	at e.$executeContributedCommand (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:628:295)
	at e._doInvokeHandler (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:788:757)
	at e._invokeHandler (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:788:449)
	at e._receiveRequest (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:787:120)
	at e._receiveOneMessage (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:970)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:784:213
	at e.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:232:615)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:957:179
	at e.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:232:615)
	at t.PersistentProtocol._receiveMessage (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:237:17)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:234:155
	at e.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at p.acceptChunk (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:230:129)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:229:483
	at Socket.t (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:238:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) withoutGuns.takeTheGuns`

The extension is obviously not compatible anymore with the newer versions of VSCode. I'll have to take a look and update it accordingly.
